### PR TITLE
Dune 3 & CI updates

### PR DESCRIPTION
**Pull request by MisterDA**

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
The 4.06 failure is caused by dune lower bounds (is it worthwhile keeping 4.06?)
```shell
 C:\Windows\system32\cmd.exe /D /S /C "D:\cygwin\wrapperbin\opam.cmd depext winsvc"
  # Detecting depexts using vars: arch=x86_64, os=win32, os-distribution=cygwinports, os-family=windows
  [ERROR] No solution for winsvc: The following dependencies couldn't be met:
            - winsvc -> dune >= 3.5 -> ocamlfind-secondary
                unknown package
            - winsvc -> dune >= 3.5 -> ocaml >= 4.08
                base of this switch (use `--unlock-base' to force)
  
  
  Command failed: opam list --readonly --external  "--resolve=winsvc" returned 20
  Error: The process 'D:\cygwin\wrapperbin\opam.cmd' failed with exit code 20
```

**Comment by MisterDA** [comment]
> is it worthwhile keeping 4.06?

no.
So many fixes for Windows got into 4.13-4.14 that using anything else is shooting yourself in your broken foot.

I've lowered the Dune lower-bound to 3.0, that's all that's needed really. I've also removed testing for 4.06.

**Comment by tmcgilchrist** [comment]
Is it possible to get this fix merged as well @toots ?

**Review by toots — APPROVED** [review]
Thanks!

**Comment by toots** [comment]
> Is it possible to get this fix merged as well @toots ?

Just did!

Would you be interested in taking over the maintenance for this one?

**Comment by tmcgilchrist** [comment]
@toots happy to help maintain this, we are using it for a few Windows infrastructure things. @MisterDA is more knowledgable about Windows things than I am.

**Comment by toots** [comment]
Great. I invited both of y'all as maintainers.

**Pull request merged**
